/**
 * Status:
 *   0: In stock
 *   10: Recommended
 *
 * @param knex
 * @param Promise
 */
exports.seed = function (knex, Promise) {
    return Promise.join(
        // Deletes ALL existing entries
        knex('books').del(),

        // Inserts seed entries
        knex('books').insert({
            id: 1,
            title: '商道大拿  ',
            pub_info: '西南财经大学出版社',
            isbn: '9787550421646',
            lend_count: 5,
            total_lend_count: 200,
            author: '俞越',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            id: 2,
            title: '斯通纳  ',
            pub_info: '上海人民出版社',
            isbn: '9787208130500',
            lend_count: 5,
            total_lend_count: 200,
            author: '约翰·威廉斯',
            stock: 20,
            pub_year: 2016,
            category_char: 'I'
        }),
        knex('books').insert({
            id: 3,
            title: '一个人的朝圣（套装共2册 京东专供）  ',
            pub_info: '北京联合出版公司',
            isbn: '11796459',
            lend_count: 5,
            total_lend_count: 200,
            author: '蕾秋·乔伊斯',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            id: 4,
            title: '马尔克斯:世上最美的溺水者  ',
            pub_info: '南海出版公司',
            isbn: '9787544280907',
            lend_count: 5,
            total_lend_count: 200,
            author: '〔哥伦比亚〕加西亚·马尔克斯',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            id: 5,
            title: '青青子衿  ',
            pub_info: '漓江出版社',
            isbn: '9787540771973',
            lend_count: 5,
            total_lend_count: 200,
            author: '胡马依',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            id: 6,
            title: '芈月传（典藏套装版 共6册）  ',
            pub_info: '浙江文艺出版社',
            isbn: '9787533943059',
            lend_count: 5,
            total_lend_count: 200,
            author: '蒋胜男',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            id: 7,
            title: '谢谢自己够勇敢（京东定制版，附赠张皓宸/杨杨勇气旅行纪念影册）  ',
            pub_info: '江西人民出版社',
            isbn: '9787210079026',
            lend_count: 5,
            total_lend_count: 200,
            author: '张皓宸',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            id: 8,
            title: '且将生活一饮而尽  ',
            pub_info: '中国华侨出版社',
            isbn: '9787511356949',
            lend_count: 5,
            total_lend_count: 200,
            author: '李座峰',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            id: 9,
            title: '白岩松：白说（京东版本，随机附赠同封笔记本并随书带二维码下载白岩松珍贵音频）  ',
            pub_info: '长江文艺出版社',
            isbn: '9787535481108',
            lend_count: 5,
            total_lend_count: 200,
            author: '白岩松',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            id: 10,
            title: '高铁风云录/首部世界高铁发展史  ',
            pub_info: '湖南文艺出版社',
            isbn: '9787540473402',
            lend_count: 5,
            total_lend_count: 200,
            author: '高铁见闻',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '孤独是生命的礼物  ',
            pub_info: '百花洲文艺出版社',
            isbn: '9787550013742',
            lend_count: 5,
            total_lend_count: 200,
            author: '余秋雨',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '坐在路边鼓掌的人  ',
            pub_info: '中信出版集团',
            isbn: '9787508647388',
            lend_count: 5,
            total_lend_count: 200,
            author: '刘继荣',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '没有人会因为心碎而绝望  ',
            pub_info: '武汉出版社',
            isbn: '9787543096332',
            lend_count: 5,
            total_lend_count: 200,
            author: '银谷',
            stock: 20,
            pub_year: 2016,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '小井想要一部时光机（京东签章版 附赠井柏然超值续写故事本）  ',
            pub_info: '湖南文艺出版社',
            isbn: '9787540471699',
            lend_count: 5,
            total_lend_count: 200,
            author: '井柏然',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '曾少年（套装上下册）  ',
            pub_info: '江苏凤凰文艺出版社',
            isbn: '9787539979397',
            lend_count: 5,
            total_lend_count: 200,
            author: '九夜茴',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '这世界，缺你不可（随机赠送吴大伟亲笔签名本）  ',
            pub_info: '湖南文艺出版社',
            isbn: '9787540472900',
            lend_count: 5,
            total_lend_count: 200,
            author: '吴大伟',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '失眠书  ',
            pub_info: '中国友谊出版社',
            isbn: '9787505736016',
            lend_count: 5,
            total_lend_count: 200,
            author: '魏小河',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '无法直视  ',
            pub_info: '中国文联出版社',
            isbn: '9787519001957',
            lend_count: 5,
            total_lend_count: 200,
            author: '夏茗悠',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '当你生病时，你会想起谁？  ',
            pub_info: '长江文艺出版社',
            isbn: '9787535482495',
            lend_count: 5,
            total_lend_count: 200,
            author: '病房',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '我只是敢和别人不一样  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550250512',
            lend_count: 5,
            total_lend_count: 200,
            author: '周宏翔',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '刘晓庆：人生不怕从头再来  ',
            pub_info: '长江文艺出版社',
            isbn: '9787535483133',
            lend_count: 5,
            total_lend_count: 200,
            author: '刘晓庆',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '那些年，我们一起追的球星：我们的青春，我们的足球时代（全彩，天下足球 开播15周年典藏版）  ',
            pub_info: '金城出版社',
            isbn: '9787515512938',
            lend_count: 5,
            total_lend_count: 200,
            author: '《天下足球》',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '亚历克斯·弗格森：我的自传（增补版）  ',
            pub_info: '北京出版社',
            isbn: '9787200114072',
            lend_count: 5,
            total_lend_count: 200,
            author: '亚历克斯·弗格森',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '曾国藩·曾文正公家书（套装上下册 附家训2卷）  ',
            pub_info: '线装书局',
            isbn: '9787512017870',
            lend_count: 5,
            total_lend_count: 200,
            author: '曾国藩',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '成龙：还没长大就老了  ',
            pub_info: '江苏凤凰文艺出版社',
            isbn: '9787539981697',
            lend_count: 5,
            total_lend_count: 200,
            author: '成龙',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '宿命：孤独张艺谋（双封面版本）  ',
            pub_info: '长江文艺出版社',
            isbn: '9787535478696',
            lend_count: 5,
            total_lend_count: 200,
            author: '周晓枫',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '幾米台历：月亮的记忆（正版授权幾米2016年台历套装《月亮忘记了》；含“最重要的80天”记事表单）  ',
            pub_info: '海豚出版社',
            isbn: '9787511026187',
            lend_count: 5,
            total_lend_count: 200,
            author: '幾米',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '快把我哥带走  ',
            pub_info: '中国友谊出版公司',
            isbn: '9787505735873',
            lend_count: 5,
            total_lend_count: 200,
            author: '幽.灵',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '阿兰的战争（套装1-3册）  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550251281',
            lend_count: 5,
            total_lend_count: 200,
            author: '埃曼努埃尔·吉贝尔',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '嗷大喵真棒：欢腾篇 一起来嗨  ',
            pub_info: '湖南文艺出版社',
            isbn: '9787540473174',
            lend_count: 5,
            total_lend_count: 200,
            author: '慕容嗷嗷',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '其实你很好，你自己却不知道  ',
            pub_info: '江苏凤凰文艺出版社',
            isbn: '9787539986753',
            lend_count: 5,
            total_lend_count: 200,
            author: '失控的Saner',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '熟女养成日志  ',
            pub_info: '北京理工大字出版社',
            isbn: '9787568209007',
            lend_count: 5,
            total_lend_count: 200,
            author: '熊顿',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '忘记亲一下  ',
            pub_info: '现代出版社',
            isbn: '9787514339512',
            lend_count: 5,
            total_lend_count: 200,
            author: '几米',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '白岩松：白说（京东版本，随机附赠同封笔记本并随书带二维码下载白岩松珍贵音频）  ',
            pub_info: '长江文艺出版社',
            isbn: '9787535481108',
            lend_count: 5,
            total_lend_count: 200,
            author: '白岩松',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '一个人的朝圣2：奎妮的情歌  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550249202',
            lend_count: 5,
            total_lend_count: 200,
            author: '蕾秋·乔伊斯',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '大冰新畅销作品 （套装共2册）  ',
            pub_info: '湖南文艺出版社',
            isbn: '11743691',
            lend_count: 5,
            total_lend_count: 200,
            author: '大冰',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '清明上河图密码2：隐藏在千古名画中的阴谋与杀局  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550258235',
            lend_count: 5,
            total_lend_count: 200,
            author: '冶文彪',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '而立·24  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550260917',
            lend_count: 5,
            total_lend_count: 200,
            author: '张艺兴',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '银河帝国：基地七部曲（新版）  ',
            pub_info: '江苏凤凰文艺出版社',
            isbn: '9787539983356',
            lend_count: 5,
            total_lend_count: 200,
            author: '艾萨克·阿西莫夫',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '东野圭吾天王套装（套装共4册）  ',
            pub_info: '南海出版公司',
            isbn: '11691118',
            lend_count: 5,
            total_lend_count: 200,
            author: '东野圭吾',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '岛上书店  ',
            pub_info: '江苏凤凰文艺出版社',
            isbn: '9787539971810',
            lend_count: 5,
            total_lend_count: 200,
            author: '加布瑞埃拉·泽文',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '大冰新畅销作品 （套装共2册）  ',
            pub_info: '湖南文艺出版社',
            isbn: '11743691',
            lend_count: 5,
            total_lend_count: 200,
            author: '大冰',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '这边风景（套装上下册）  ',
            pub_info: '广东花城出版社',
            isbn: '9787536067417',
            lend_count: 5,
            total_lend_count: 200,
            author: '王蒙',
            stock: 20,
            pub_year: 2013,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '繁花（全本珍藏版）  ',
            pub_info: '上海文艺出版社',
            isbn: '9787532148004',
            lend_count: 5,
            total_lend_count: 200,
            author: '金宇澄',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '鲁迅全集（插图本 套装1-20卷）  ',
            pub_info: '同心出版社',
            isbn: '9787547711101',
            lend_count: 5,
            total_lend_count: 200,
            author: '鲁迅',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '唐宋词鉴赏辞典（第二版 套装共2册）  ',
            pub_info: '上海辞书出版社',
            isbn: '9787532632220',
            lend_count: 5,
            total_lend_count: 200,
            author: '周汝昌',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '此生未完成  ',
            pub_info: '湖南科学技术出版社',
            isbn: '9787535766779',
            lend_count: 5,
            total_lend_count: 200,
            author: '于娟',
            stock: 20,
            pub_year: 2011,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '不忘初心，方得始终  ',
            pub_info: '长江文艺出版社',
            isbn: '9787535466129',
            lend_count: 5,
            total_lend_count: 200,
            author: '凌茜',
            stock: 20,
            pub_year: 2013,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '皮囊  ',
            pub_info: '天津人民出版社',
            isbn: '9787201088945',
            lend_count: 5,
            total_lend_count: 200,
            author: '蔡崇达',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '失眠书  ',
            pub_info: '中国友谊出版社',
            isbn: '9787505736016',
            lend_count: 5,
            total_lend_count: 200,
            author: '魏小河',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '壹刻：李易峰最好的时光  ',
            pub_info: '金城出版社',
            isbn: '9787515511139',
            lend_count: 5,
            total_lend_count: 200,
            author: '李易峰',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '孤独是你的必修课  ',
            pub_info: '江苏凤凰文艺出版社',
            isbn: '9787539974736',
            lend_count: 5,
            total_lend_count: 200,
            author: '崔佳',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '来自星星的EXO  ',
            pub_info: '北京时代华文书局',
            isbn: '9787807695479',
            lend_count: 5,
            total_lend_count: 200,
            author: '星星狂魔',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '三重门（纪念版）  ',
            pub_info: '作家出版社',
            isbn: '9787506341035',
            lend_count: 5,
            total_lend_count: 200,
            author: '韩寒',
            stock: 20,
            pub_year: 2007,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '滚雪球：巴菲特和他的财富人生（套装共2册）  ',
            pub_info: '中信出版社',
            isbn: '11552470',
            lend_count: 5,
            total_lend_count: 200,
            author: '艾丽斯·施罗德',
            stock: 20,
            pub_year: 2013,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '大清三重臣（套装共3册）  ',
            pub_info: '中国民主法制出版社',
            isbn: '9787516203446',
            lend_count: 5,
            total_lend_count: 200,
            author: '纪连海',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '最后的黑曼巴：科比·布莱恩特全传  ',
            pub_info: '北京时代华文书局',
            isbn: '9787569903133',
            lend_count: 5,
            total_lend_count: 200,
            author: '冯逸明',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '苹果上的缺口  ',
            pub_info: '江苏凤凰文艺出版社',
            isbn: '9787539980935',
            lend_count: 5,
            total_lend_count: 200,
            author: '克里斯安·布伦南',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '大卫·贝克汉姆（精装珍藏版）  ',
            pub_info: '新世界出版社',
            isbn: '9787510448324',
            lend_count: 5,
            total_lend_count: 200,
            author: '大卫·贝克汉姆',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '群星闪耀时·这个时代的足坛巨星·红：内维尔自传  ',
            pub_info: '新世界出版社',
            isbn: '9787510454158',
            lend_count: 5,
            total_lend_count: 200,
            author: '加里·内维尔',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '银魂（第1部）（盒装1-28卷）  ',
            pub_info: '中国美术出版总社',
            isbn: '11172716',
            lend_count: 5,
            total_lend_count: 200,
            author: '梁晓岩',
            stock: 20,
            pub_year: 2012,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '睡不着：Tango一日一画  ',
            pub_info: '中信出版社',
            isbn: '9787508643304',
            lend_count: 5,
            total_lend_count: 200,
            author: 'Tango',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '熊顿作品全集含滚蛋吧！肿瘤君纪念珍藏套装（套装共6册 熊顿作品全集）  ',
            pub_info: '北京理工大学出版社',
            isbn: '11730555',
            lend_count: 5,
            total_lend_count: 200,
            author: '熊顿',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '阿狸·尾巴（赠送精美卡片、Hans亲笔手写体书签）  ',
            pub_info: '中国华侨出版社',
            isbn: '9787511340672',
            lend_count: 5,
            total_lend_count: 200,
            author: 'Hans',
            stock: 20,
            pub_year: 2013,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '岛上书店  ',
            pub_info: '江苏凤凰文艺出版社',
            isbn: '9787539971810',
            lend_count: 5,
            total_lend_count: 200,
            author: '加布瑞埃拉·泽文',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '琅琊榜（套装共3册）  ',
            pub_info: '四川文艺出版社',
            isbn: '9787541132506',
            lend_count: 5,
            total_lend_count: 200,
            author: '海宴',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '阿弥陀佛么么哒  ',
            pub_info: '湖南文艺出版社',
            isbn: '9787540472238',
            lend_count: 5,
            total_lend_count: 200,
            author: '大冰',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '白岩松：白说（京东版本，随机附赠同封笔记本并随书带二维码下载白岩松珍贵音频）  ',
            pub_info: '长江文艺出版社',
            isbn: '9787535481108',
            lend_count: 5,
            total_lend_count: 200,
            author: '白岩松',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '盗墓笔记1-8（六周年纪念版 全套共9册）  ',
            pub_info: '上海文化出版社',
            isbn: '11026413',
            lend_count: 5,
            total_lend_count: 200,
            author: '南派三叔',
            stock: 20,
            pub_year: 2011,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '严歌苓作品集（套装全10册）  ',
            pub_info: '陕西师范大学出版社',
            isbn: '11620690',
            lend_count: 5,
            total_lend_count: 200,
            author: '严歌苓',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '中国古典文学读本丛书：四大名著权威定本（红楼梦+三国演义+水浒传+西游记）（套装共8册）  ',
            pub_info: '人民文学出版社',
            isbn: '11253398',
            lend_count: 5,
            total_lend_count: 200,
            author: '吴承恩',
            stock: 20,
            pub_year: 2008,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '人生三书：孩子你慢慢来·亲爱的安德烈·目送（布面典藏版 套装共3册）  ',
            pub_info: '广西师范大学出版社',
            isbn: '9787549555840',
            lend_count: 5,
            total_lend_count: 200,
            author: '龙应台',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '莎士比亚全集（精装本1-8卷）（增补本）  ',
            pub_info: '译林出版社',
            isbn: '9787805677859',
            lend_count: 5,
            total_lend_count: 200,
            author: '莎士比亚',
            stock: 20,
            pub_year: 2012,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '二战德军三大文件：闪击英雄+失去的胜利+隆美尔战时文件（套装共3册）  ',
            pub_info: '民主与建设出版社',
            isbn: '11763019',
            lend_count: 5,
            total_lend_count: 200,
            author: '冯·埃里希·曼施泰因',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '滚雪球：巴菲特和他的财富人生（套装共2册）  ',
            pub_info: '中信出版社',
            isbn: '11552470',
            lend_count: 5,
            total_lend_count: 200,
            author: '艾丽斯·施罗德',
            stock: 20,
            pub_year: 2013,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '忘川（附赠ENO亲绘限量版血薇夕影明信片 套装共2册）  ',
            pub_info: '北京联合出版公司',
            isbn: '11560754',
            lend_count: 5,
            total_lend_count: 200,
            author: '沧月',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '魔兽世界·官方小说典藏版（套装共3册）  ',
            pub_info: '新星出版社',
            isbn: '9787513315500',
            lend_count: 5,
            total_lend_count: 200,
            author: '克里斯蒂·高登',
            stock: 20,
            pub_year: 2014,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '熊顿作品全集含滚蛋吧！肿瘤君纪念珍藏套装（套装共6册 熊顿作品全集）  ',
            pub_info: '北京理工大学出版社',
            isbn: '11730555',
            lend_count: 5,
            total_lend_count: 200,
            author: '熊顿',
            stock: 20,
            pub_year: 2015,
            category_char: 'I'
        }),
        knex('books').insert({
            title: '如何改变世界：马克思和马克思主义的传奇  ',
            pub_info: '中央编译出版社',
            isbn: '9787511719843',
            lend_count: 1,
            total_lend_count: 100,
            author: '埃里克·霍布斯鲍姆',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '毛泽东与林彪：半世纪的恩怨（修订版）  ',
            pub_info: '东方出版社',
            isbn: '9787506082266',
            lend_count: 1,
            total_lend_count: 100,
            author: '叶健君',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思主义理论研究和建设工程重点教材：马克思主义发展史  ',
            pub_info: '高等教育出版社',
            isbn: '9787040378726',
            lend_count: 1,
            total_lend_count: 100,
            author: '《马克思主义发展史》编写组',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '中国为什么还需要马克思主义：答关于马克思主义的十大疑问  ',
            pub_info: '天津人民出版社',
            isbn: '9787201078700',
            lend_count: 1,
            total_lend_count: 100,
            author: '陈学明',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思主义理论研究和建筑工程重点教材：中国马克思主义与当代（2013年修订版）  ',
            pub_info: '高等教育出版社',
            isbn: '9787040383836',
            lend_count: 1,
            total_lend_count: 100,
            author: '《中国马克思主义与当代》编写组',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '资本主义与现代社会理论：对马克思、涂尔干和韦伯著作的分析  ',
            pub_info: '上海译文出版社',
            isbn: '9787532760367',
            lend_count: 1,
            total_lend_count: 100,
            author: '安东尼·吉登斯',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思的事业：从布鲁塞尔到北京  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300161204',
            lend_count: 1,
            total_lend_count: 100,
            author: '韩毓海',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '青年们，读马克思吧！  ',
            pub_info: '红旗出版社',
            isbn: '9787505124653',
            lend_count: 1,
            total_lend_count: 100,
            author: '内田树',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思恩格斯文集（套装共10卷）（普及本）  ',
            pub_info: '人民出版社',
            isbn: '9787010085807',
            lend_count: 1,
            total_lend_count: 100,
            author: '中共中央马克思恩格斯列宁斯大林著作编译局',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思主义基本原理概论（修订版）  ',
            pub_info: '经济科学出版社',
            isbn: '9787514142082',
            lend_count: 1,
            total_lend_count: 100,
            author: '邓晓辉',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思恩格斯全集（第30卷）  ',
            pub_info: '人民出版社',
            isbn: '9787010012926 ',
            lend_count: 1,
            total_lend_count: 100,
            author: '中共中央马克思恩格斯列宁斯大林著作编译局',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '毛泽东文集（第3卷）  ',
            pub_info: '人民出版社',
            isbn: '9787010021713 ',
            lend_count: 1,
            total_lend_count: 100,
            author: '中共中央文献研究室',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '经典悦读系列丛书：思维的法则  毛泽东《矛盾论》如是读  ',
            pub_info: '广东人民出版社',
            isbn: '9787218095387',
            lend_count: 1,
            total_lend_count: 100,
            author: '陈培永',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '毛泽东选集（第4卷）（平装）  ',
            pub_info: '人民出版社',
            isbn: '9787010009254 ',
            lend_count: 1,
            total_lend_count: 100,
            author: '毛泽东',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '毛泽东：雄关漫道（套装上下册）（插图本）  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300198316',
            lend_count: 1,
            total_lend_count: 100,
            author: '阿兰·鲁林',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思主义基本观点18讲  ',
            pub_info: '中国社会科学出版社',
            isbn: '9787500494843',
            lend_count: 1,
            total_lend_count: 100,
            author: '赵甲明',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '经典悦读系列丛书：认识的智慧  毛泽东《实践论》如是读  ',
            pub_info: '广东人民出版社',
            isbn: '9787218095363',
            lend_count: 1,
            total_lend_count: 100,
            author: '陈培永',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '历史的借鉴：毛泽东评述中国历代帝王  ',
            pub_info: '新华出版社',
            isbn: '9787501186822',
            lend_count: 1,
            total_lend_count: 100,
            author: '邸延生',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '普通高等教育“十五”国家极规划教材：邓小平理论和三个代表重要思想概论  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300057958',
            lend_count: 1,
            total_lend_count: 100,
            author: '徐志宏',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '邓小平智慧  ',
            pub_info: '人民出版社',
            isbn: '9787010142425',
            lend_count: 1,
            total_lend_count: 100,
            author: '萧诗美',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思的意识形态批判与当代中国  ',
            pub_info: '中国社会科学出版社',
            isbn: '9787500484196',
            lend_count: 1,
            total_lend_count: 100,
            author: '侯惠勤',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '毛泽东文集（第3卷）  ',
            pub_info: '人民出版社',
            isbn: '9787010021690 ',
            lend_count: 1,
            total_lend_count: 100,
            author: '中共中央文献研究室',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思的复仇：资本主义的复苏和苏联集权社会主义的灭亡  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300092171 ',
            lend_count: 1,
            total_lend_count: 100,
            author: '梅格纳德·德赛',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '人文与社会译丛·马克思主义与历史学：一种批判性的研究  [Marxism and History:A Critical Introduction]',
            pub_info: '译林出版社',
            isbn: '9787544727068',
            lend_count: 1,
            total_lend_count: 100,
            author: 'S.H.里格比',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '经典悦读系列丛书：驾驭矛盾的技艺  毛泽东《关于正确处理人民内部矛盾的问题》如是读  ',
            pub_info: '广东人民出版社',
            isbn: '9787218095424',
            lend_count: 1,
            total_lend_count: 100,
            author: '梁道刚',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思恩格斯全集（第32卷）  ',
            pub_info: '人民出版社',
            isbn: '9787010023748 ',
            lend_count: 1,
            total_lend_count: 100,
            author: '中共中央马克思恩格斯列宁斯大林作编译局',
            stock: 10,
            'pub_year': '套装数量：32',
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思恩格斯全集46  ',
            pub_info: '人民出版社',
            isbn: '9787010034355',
            lend_count: 1,
            total_lend_count: 100,
            author: '中共中央马克思恩格斯列宁斯大林著作编译局',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '毛泽东思想的批判性透视/马克思主义研究论库·第一辑  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300218250',
            lend_count: 1,
            total_lend_count: 100,
            author: '阿里夫·德里克',
            stock: 10,
            pub_year: 2005,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思恩格斯全集（第44卷）  ',
            pub_info: '人民出版社',
            isbn: '9787010028637',
            lend_count: 1,
            total_lend_count: 100,
            author: '马克思',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '马克思主义价值观研究  ',
            pub_info: '人民出版社',
            isbn: '9787010125152',
            lend_count: 1,
            total_lend_count: 100,
            author: '罗国杰',
            stock: 10,
            pub_year: 2013,
            category_char: 'A',
            status: 0
        }),
        knex('books').insert({
            title: '退一步，并不难  ',
            pub_info: '中国商业出版社',
            isbn: '9787504489975',
            lend_count: 10,
            total_lend_count: 500,
            author: '达照',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '哲学家们都干了些什么？  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550242234',
            lend_count: 10,
            total_lend_count: 500,
            author: '林欣浩',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '你在忙什么  ',
            pub_info: '民主与建设出版社',
            isbn: '9787513905855',
            lend_count: 10,
            total_lend_count: 500,
            author: '索达吉堪布',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '漫谈弟子规  ',
            pub_info: '三秦出版社',
            isbn: '9787551801638',
            lend_count: 10,
            total_lend_count: 500,
            author: '索达吉堪布',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '哲学纲要  ',
            pub_info: '中华书局',
            isbn: '9787101109986',
            lend_count: 10,
            total_lend_count: 500,
            author: '李泽厚',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '阿德勒100句人生革命  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550262867',
            lend_count: 10,
            total_lend_count: 500,
            author: '阿德勒',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '吴建民谈外交  ',
            pub_info: '中信出版集团',
            isbn: '9787508654997',
            lend_count: 10,
            total_lend_count: 500,
            author: '吴建民',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '论语译注（典藏版）  ',
            pub_info: '中华书局',
            isbn: '9787101107784',
            lend_count: 10,
            total_lend_count: 500,
            author: '杨伯峻',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '一切都是最好的安排  ',
            pub_info: '中国友谊出版公司',
            isbn: '9787505729230',
            lend_count: 10,
            total_lend_count: 500,
            author: '加措',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '与神对话 1（全新修订版）  [CONVERSATIONS WITH GOD: BOOK ONE]',
            pub_info: '江西人民出版社',
            isbn: '9787210071976',
            lend_count: 10,
            total_lend_count: 500,
            author: '尼尔·唐纳德·沃尔什',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '儒教哲学丛书：天人合一正义  ',
            pub_info: '中华书局',
            isbn: '9787101109047',
            lend_count: 10,
            total_lend_count: 500,
            author: '蒲创国',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '论语心读（修订本）  ',
            pub_info: '中华书局',
            isbn: '9787101111705',
            lend_count: 10,
            total_lend_count: 500,
            author: '柳恩铭',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '生死功课  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550242791',
            lend_count: 10,
            total_lend_count: 500,
            author: 'Erika',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '图解易经：读懂中国文化第一书（经典图解畅销版）  ',
            pub_info: '江西科学技术出版社',
            isbn: '9787539044750',
            lend_count: 10,
            total_lend_count: 500,
            author: '高永平',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '心智的力量  ',
            pub_info: '长江文艺出版公司',
            isbn: '9787535478900',
            lend_count: 10,
            total_lend_count: 500,
            author: '吉杜·克里希那穆提',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '你将成为自己的光  ',
            pub_info: '长江文艺出版公司',
            isbn: '9787535478894',
            lend_count: 10,
            total_lend_count: 500,
            author: '吉杜·克里希那穆提',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '一切都是最好的安排  ',
            pub_info: '中国友谊出版公司',
            isbn: '9787505729230',
            lend_count: 10,
            total_lend_count: 500,
            author: '加措',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '觉悟：星云大师的心灵修行课  ',
            pub_info: '线装书局',
            isbn: '9787512005334',
            lend_count: 10,
            total_lend_count: 500,
            author: '星云大师',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '佛经故事  ',
            pub_info: '中华书局',
            isbn: '9787101093186',
            lend_count: 10,
            total_lend_count: 500,
            author: '王邦维',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '一切都是最好的安排  ',
            pub_info: '中国友谊出版公司',
            isbn: '9787505729230',
            lend_count: 10,
            total_lend_count: 500,
            author: '加措',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '中国哲学简史  ',
            pub_info: '北京大学出版社',
            isbn: '9787301215692',
            lend_count: 10,
            total_lend_count: 500,
            author: '冯友兰',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '中国哲学史（套装上下册）  ',
            pub_info: '重庆出版社',
            isbn: '9787229012632',
            lend_count: 10,
            total_lend_count: 500,
            author: '冯友兰',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '西藏生死书  ',
            pub_info: '浙江大学出版社',
            isbn: '9787308083782',
            lend_count: 10,
            total_lend_count: 500,
            author: '索甲仁波切',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '道德经大全集  ',
            pub_info: '新世界出版社',
            isbn: '9787510414176',
            lend_count: 10,
            total_lend_count: 500,
            author: '老子',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '你的第一本哲学书  [What Does It All Mean]',
            pub_info: '当代中国出版社',
            isbn: '9787801703637',
            lend_count: 10,
            total_lend_count: 500,

            author: '托马斯·内格尔',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '论语译注  ',
            pub_info: '中华书局',
            isbn: '9787101054194',
            lend_count: 10,
            total_lend_count: 500,
            author: '杨伯峻',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '礼品装家庭必读书 周易（套装共6册）  ',
            pub_info: '辽海出版社',
            isbn: '9787545115376',
            lend_count: 10,
            total_lend_count: 500,
            author: '《礼品装家庭必读书》编委会',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '万万没想到 用理工科思维理解世界 入选2014中国好书  ',
            pub_info: '电子工业出版社',
            isbn: '9787121242151',
            lend_count: 10,
            total_lend_count: 500,
            author: '万维钢',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '心灵的平和之美  ',
            pub_info: '长江文艺出版社',
            isbn: '9787535478917',
            lend_count: 10,
            total_lend_count: 500,
            author: '克里希那穆提',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '自在  ',
            pub_info: '甘肃人民美术出版社',
            isbn: '9787552702910',
            lend_count: 10,
            total_lend_count: 500,

            author: '星云大师',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '你将成为自己的光  ',
            pub_info: '长江文艺出版公司',
            isbn: '9787535478894',
            lend_count: 10,
            total_lend_count: 500,
            author: '吉杜·克里希那穆提',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '龙泉寺学诚法师漫画哲学书：放下是舍更是得+烦恼都是自找的+快乐就这么简单（套装全3册）  ',
            pub_info: '华文出版社',
            isbn: '11783474',
            lend_count: 10,
            total_lend_count: 500,
            author: '学诚法师',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '狡猾的思想  ',
            pub_info: '长江文艺出版社',
            isbn: '9787535478924',
            lend_count: 10,
            total_lend_count: 500,
            author: '吉杜·克里希那穆提',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '西方哲学史(套装上下册 网店专供）  ',
            pub_info: '商务印书馆',
            isbn: '11757004',
            lend_count: 10,
            total_lend_count: 500,
            author: '罗素',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '西方哲学史(套装上下册 网店专供）  ',
            pub_info: '商务印书馆',
            isbn: '11757004',
            lend_count: 10,
            total_lend_count: 500,
            author: '罗素',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '退一步，并不难  ',
            pub_info: '中国商业出版社',
            isbn: '9787504489975',
            lend_count: 10,
            total_lend_count: 500,
            author: '达照',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '王阳明心学：典藏修订版  ',
            pub_info: '民主与建设出版社',
            isbn: '9787513906708',
            lend_count: 10,
            total_lend_count: 500,
            author: '王觉仁',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '论人类不平等的起源和基础  ',
            pub_info: '浙江文艺出版社',
            isbn: '9787533941833',
            lend_count: 10,
            total_lend_count: 500,
            author: '让-雅克·卢梭',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '万万没想到 用理工科思维理解世界（限量签名版）  ',
            pub_info: '电子工业出版社',
            isbn: '9787121242151',
            lend_count: 10,
            total_lend_count: 500,
            author: '万维钢',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '阿德勒100句人生革命  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550262867',
            lend_count: 10,
            total_lend_count: 500,
            author: '阿德勒',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '哲学家们都干了些什么？  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550242234',
            lend_count: 10,
            total_lend_count: 500,
            author: '林欣浩',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '王阳明最神奇的心学  ',
            pub_info: '中国华侨出版社',
            isbn: '9787511327192',
            lend_count: 10,
            total_lend_count: 500,
            author: '王阳明<原著>',
            stock: 30,
            pub_year: 2014,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '耶鲁大学公开课：死亡  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550227392',
            lend_count: 10,
            total_lend_count: 500,
            author: '谢利·卡根',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '古兰经+古兰经注（套装共2册）  ',
            pub_info: '中国社会科学出版社',
            isbn: '11743510',
            lend_count: 10,
            total_lend_count: 500,
            author: '马坚',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '西方哲学史(套装上下册 网店专供）  ',
            pub_info: '商务印书馆',
            isbn: '11757004',
            lend_count: 10,
            total_lend_count: 500,
            author: '罗素',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '西方哲学史(套装上下册 网店专供）  ',
            pub_info: '商务印书馆',
            isbn: '11757004',
            lend_count: 10,
            total_lend_count: 500,
            author: '罗素',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }),
        knex('books').insert({
            title: '中国哲学简史  ',
            pub_info: '北京大学出版社',
            isbn: '9787301215692',
            lend_count: 10,
            total_lend_count: 500,
            author: '冯友兰',
            stock: 30,
            pub_year: 2015,
            category_char: 'B',
            status: 0
        }), knex('books').insert({
            title: '娱乐至死  [Amusing ourselves to death]',
            pub_info: '中信出版集团',
            isbn: '9787508648286',
            lend_count: 5,
            total_lend_count: 250,
            author: '尼尔·波兹曼',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '哈佛非虚构写作课:怎样讲好一个故事  ',
            pub_info: '中国文史出版社',
            isbn: '9787503466779',
            lend_count: 5,
            total_lend_count: 250,
            author: '马克·克雷默',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '理解媒介：论人的延伸（增订评注本）  ',
            pub_info: '译林出版社',
            isbn: '9787544717779',
            lend_count: 5,
            total_lend_count: 250,
            author: '马歇尔·麦克卢汉',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '一个人与这个时代：白岩松二十年央视成长记录一个时代变迁备忘  ',
            pub_info: '上海交通大学出版社',
            isbn: '9787313103932',
            lend_count: 5,
            total_lend_count: 250,
            author: '邹煜',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '巴黎烧了吗？  ',
            pub_info: '译林出版社',
            isbn: '9787544736183',
            lend_count: 5,
            total_lend_count: 250,
            author: '拉莱·科林斯',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '不要因为走得太远而忘记为什么出发：陈虻，我们听你讲  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300168098',
            lend_count: 5,
            total_lend_count: 250,
            author: '徐泓',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '文雅的疯狂  ',
            pub_info: '上海人民出版社',
            isbn: '9787208124868',
            lend_count: 5,
            total_lend_count: 250,
            author: '尼古拉斯·A. 巴斯贝恩',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '传播学教程（第2版）/普通高等教育“十一五”国家级规划教材·21世纪新闻传播学系列教材  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300111254',
            lend_count: 5,
            total_lend_count: 250,
            author: '郭庆光',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '新闻报道与写作（插图第11版）  ',
            pub_info: '世界图书出版公司',
            isbn: '9787510065583',
            lend_count: 5,
            total_lend_count: 250,
            author: '梅尔文·门彻',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '人民日报传媒书系：一本书学会新闻写作  ',
            pub_info: '人民日报出版社',
            isbn: '9787511507204',
            lend_count: 5,
            total_lend_count: 250,
            author: '卞丽敏',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '新闻写作教程/21世纪新闻传播学系列教材  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300039817',
            lend_count: 5,
            total_lend_count: 250,
            author: '刘明华',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '当代世界学术名著·新闻与传播学译丛·大师经典系列：传播学概论（第2版）  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300122144',
            lend_count: 5,
            total_lend_count: 250,
            author: '威尔伯·施拉姆',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '沉默的螺旋：舆论我们的社会皮肤  ',
            pub_info: '北京大学出版社',
            isbn: '9787301200346',
            lend_count: 5,
            total_lend_count: 250,
            author: '伊丽莎白·诺尔-诺依曼',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '文博教材：中国博物馆学基础（修订本）  ',
            pub_info: '上海古籍出版社',
            isbn: '9787532530120',
            lend_count: 5,
            total_lend_count: 250,
            author: '王宏钧',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '时评写作十讲  ',
            pub_info: '复旦大学出版社',
            isbn: '9787309082029',
            lend_count: 5,
            total_lend_count: 250,
            author: '曹林',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '图书编辑校对实用手册（第三版）  ',
            pub_info: '广西师范大学出版社',
            isbn: '9787549554799',
            lend_count: 5,
            total_lend_count: 250,
            author: '黎洪波',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '古文献学讲义  ',
            pub_info: '中西书局',
            isbn: '9787547507117',
            lend_count: 5,
            total_lend_count: 250,
            author: '黄永年',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '中文核心期刊要目总览（2014年版）  ',
            pub_info: '北京大学出版社',
            isbn: '9787301261897',
            lend_count: 5,
            total_lend_count: 250,
            author: '朱强',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '网络传播概论（第3版）/21世纪新媒体专业系列教材  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300162386',
            lend_count: 5,
            total_lend_count: 250,
            author: '彭兰',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '新编播音员主持人训练手册：语音发声（第3版 附光盘1张）  ',
            pub_info: '中国传媒大学出版社',
            isbn: '9787565711312',
            lend_count: 5,
            total_lend_count: 250,
            author: '王璐',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '中国古文献学史（修订本 套装上下册）  ',
            pub_info: '中华书局',
            isbn: '9787101100532',
            lend_count: 5,
            total_lend_count: 250,
            author: '孙钦善',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '编辑人的世界  [Editors on Editing]',
            pub_info: '新星出版社',
            isbn: '9787513311434',
            lend_count: 5,
            total_lend_count: 250,
            author: '杰拉尔德·格罗斯',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '做书：感悟与理念  ',
            pub_info: '商务印书馆',
            isbn: '9787100115346',
            lend_count: 5,
            total_lend_count: 250,
            author: '李昕',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '青少年播音主持训练系列丛书：新编主持人话题宝典  ',
            pub_info: '中国传媒大学出版社',
            isbn: '9787565705236',
            lend_count: 5,
            total_lend_count: 250,
            author: '王文丽',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '直面媒体20年（平装本）  ',
            pub_info: '新世界出版社',
            isbn: '9787510453748',
            lend_count: 5,
            total_lend_count: 250,
            author: '赵启正',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '人民日报传媒书系·获奖评论赏析：兼谈评论的写作技巧（最新修订版）  ',
            pub_info: '人民日报出版社',
            isbn: '9787511520678',
            lend_count: 5,
            total_lend_count: 250,
            author: '刘保全',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '怎样写好文献综述：案例及评述  [How to Review Literature:Cases and Comments]',
            pub_info: '科学出版社',
            isbn: '9787030208231',
            lend_count: 5,
            total_lend_count: 250,
            author: '张黎',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '新闻的十大基本原则：新闻从业者须知和公众的期待  ',
            pub_info: '北京大学出版社',
            isbn: '9787301247518',
            lend_count: 5,
            total_lend_count: 250,
            author: '比尔·科瓦奇',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '人民日报传媒书系：通讯员新闻采写一本通  ',
            pub_info: '人民日报出版社',
            isbn: '9787511529367',
            lend_count: 5,
            total_lend_count: 250,
            author: '王卫明',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '实用粤语播音主持语言基础教程  ',
            pub_info: '中国广播电视出版社',
            isbn: '9787504364302',
            lend_count: 5,
            total_lend_count: 250,
            author: '刘玉萍',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '复旦新闻与传播学译库·理解新媒介：延伸麦克卢汉  ',
            pub_info: '复旦大学出版社',
            isbn: '9787309089530 ',
            lend_count: 5,
            total_lend_count: 250,
            author: '罗伯特·洛根',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '新闻编辑学（第三版）（21世纪新闻传播学系列教材·新闻学系列；普通高等教育“十一五”国家级规划教  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300193595',
            lend_count: 5,
            total_lend_count: 250,
            author: '蔡雯',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '品牌传播战略：数字时代的整合传播计划  ',
            pub_info: '科学出版社',
            isbn: '9787030378774',
            lend_count: 5,
            total_lend_count: 250,
            author: '杨东念',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '复旦新闻传播学译库·新媒体系列：新新媒介（第二版）  ',
            pub_info: '复旦大学出版社',
            isbn: '9787309105841',
            lend_count: 5,
            total_lend_count: 250,
            author: '保罗·莱文森',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '“十二五”普通高等教育本科国家级规划教材：传媒经济学教程  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300103259',
            lend_count: 5,
            total_lend_count: 250,
            author: '喻国明',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '博物馆之眼  ',
            pub_info: '山东美术出版社',
            isbn: '9787533033064',
            lend_count: 5,
            total_lend_count: 250,
            author: '日青',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '复旦博学·新闻与传播学系列教材：新闻学概论（第5版）  ',
            pub_info: '复旦大学出版社',
            isbn: '9787309095913',
            lend_count: 5,
            total_lend_count: 250,
            author: '李良荣',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '传播理论：起源方法与应用（第5版）/21世纪新闻传播学基础教材  ',
            pub_info: '中国传媒大学出版社',
            isbn: '9787810855631',
            lend_count: 5,
            total_lend_count: 250,
            author: '赛佛林',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '信息的骨头：数字时代的精准传播  [On Message]',
            pub_info: '电子工业出版社',
            isbn: '9787121232497',
            lend_count: 5,
            total_lend_count: 250,
            author: '西奥·西奥博尔德',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '人民日报传媒书系：人民日报任仲平80篇  ',
            pub_info: '人民日报出版社',
            isbn: '9787511523334',
            lend_count: 5,
            total_lend_count: 250,
            author: '人民日报社评论部',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '媒体世界：人类学的新领域  ',
            pub_info: '商务印书馆',
            isbn: '9787100102704',
            lend_count: 5,
            total_lend_count: 250,
            author: '费·金斯伯格',
            stock: 10,
            pub_year: 2013,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '复旦新闻与传播学译库·新媒体系列·媒介、社会与世界：社会理论与数字媒介实践  [Media， Society， World： Social Theory and Digital Media Practice]',
            pub_info: '复旦大学出版社',
            isbn: '9787309104387',
            lend_count: 5,
            total_lend_count: 250,
            author: '尼克·库尔德利',
            stock: 10,
            pub_year: 2011,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '从莎草纸到互联网：社交媒体2000年  [Writing on the Wall]',
            pub_info: '中信出版集团',
            isbn: '9787508646121',
            lend_count: 5,
            total_lend_count: 250,
            author: '汤姆·斯丹迪奇',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '书店时光：世界最美书店巡礼  [Wonderful Bookstores of the World]',
            pub_info: '新星出版社',
            isbn: '9787513310192',
            lend_count: 5,
            total_lend_count: 250,
            author: 'X-Knowledge',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '广播电视新闻采访与写作  ',
            pub_info: '北京师范大学出版社',
            isbn: '9787303082711',
            lend_count: 5,
            total_lend_count: 250,
            author: '赵淑萍',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '播音主持快速入门十八招儿  ',
            pub_info: '中国传媒大学出版社',
            isbn: '9787565701368',
            lend_count: 5,
            total_lend_count: 250,
            author: '赵秀环',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '互联网的误读（新闻与传播学译丛·学术前沿系列）  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300188621',
            lend_count: 5,
            total_lend_count: 250,
            author: '詹姆斯·柯兰',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '外国新闻传播史/21世纪新闻传播学系列教材  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300033242 ',
            lend_count: 5,
            total_lend_count: 250,
            author: '郑超然',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '全媒体时代新闻传播学系列教材：新闻评论教程（第2版）（附学习卡）  ',
            pub_info: '高等教育出版社',
            isbn: '9787040325867',
            lend_count: 5,
            total_lend_count: 250,
            author: '马少华',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '谷登堡星汉璀璨：印刷文明的诞生  [The Gutenberg Galaxy]',
            pub_info: '北京理工大学出版社',
            isbn: '9787564086374',
            lend_count: 5,
            total_lend_count: 250,
            author: '马歇尔·麦克卢汉',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '十驾斋养新录  ',
            pub_info: '上海书店出版社',
            isbn: '9787806783351',
            lend_count: 5,
            total_lend_count: 250,
            author: '钱大昕',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '版权洽谈完全手册  ',
            pub_info: '世界图书出版公司',
            isbn: '9787510090882',
            lend_count: 5,
            total_lend_count: 250,
            author: '姜汉忠',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '青海年播音主持训练系列丛书：青少年播音主持训练教程（第2版）（附光盘）  ',
            pub_info: '中国传媒大学出版社',
            isbn: '9787565707506',
            lend_count: 5,
            total_lend_count: 250,
            author: '张洁',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '播音主持语音发声训练教程/21世纪播音主持专业训练教材  ',
            pub_info: '中国传媒大学出版社',
            isbn: '9787565701320',
            lend_count: 5,
            total_lend_count: 250,
            author: '张涵',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '新媒体十讲  ',
            pub_info: '中信出版集团',
            isbn: '9787508652894',
            lend_count: 5,
            total_lend_count: 250,
            author: '范卫锋',
            stock: 10,
            pub_year: 2015,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '传播学基础：历史、框架与外延（第2版）/普通高等教育“十一五”国家级规划教材  ',
            pub_info: '中国传媒大学出版社',
            isbn: '9787565707100',
            lend_count: 5,
            total_lend_count: 250,
            author: '段鹏',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '档案管理学（第四版）  ',
            pub_info: '中国人民大学出版社',
            isbn: '9787300215075',
            lend_count: 5,
            total_lend_count: 250,
            author: '王英玮',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        knex('books').insert({
            title: '信息存储与管理（第2版）：数字信息的存储、管理和保护  ',
            pub_info: '人民邮电出版社',
            isbn: '9787115323262',
            lend_count: 5,
            total_lend_count: 250,
            author: 'G.Somasundaram',
            stock: 10,
            pub_year: 2012,
            category_char: 'C',
            status: 0
        }),
        /**
         * Created by chenyulu on 16/1/3.
         */
        knex('books').insert({
            title: '历史的绝笔：名人书信背后的历史侧影  ',
            pub_info: '四川人民出版社',
            isbn: '9787220096600',
            lend_count: 5,
            total_lend_count: 300,
            author: '叶永烈',
            stock: 10,
            pub_year: 2016,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '秩序的沦陷：抗战初期的江南五城  ',
            pub_info: '商务印书馆',
            isbn: '9787100112758',
            lend_count: 5,
            total_lend_count: 300,
            author: '卜正民',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '西洋镜：1907，北京—巴黎汽车拉力赛  ',
            pub_info: '中国画报出版社',
            isbn: '9787514611946',
            lend_count: 5,
            total_lend_count: 300,
            author: '吕吉·巴津尼',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '历史学的境界  ',
            pub_info: '广西师范大学出版社',
            isbn: '9787549571413',
            lend_count: 5,
            total_lend_count: 300,
            author: '高华',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '历史学家的经线  ',
            pub_info: '中信出版集团',
            isbn: '9787508653136',
            lend_count: 5,
            total_lend_count: 300,
            author: '孙隆基',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '魂兮归来：金一南讲抗日战争  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550254206',
            lend_count: 5,
            total_lend_count: 300,
            author: '金一南',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '第三帝国的最后十四天  ',
            pub_info: '新星出版社',
            isbn: '9787513319331',
            lend_count: 5,
            total_lend_count: 300,
            author: '约阿希姆·费斯特',
            stock: 10,
            pub_year: 2016,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '走向田野与社会（修订版）  ',
            pub_info: '生活·读书·新知三联书店',
            isbn: '9787108053268',
            lend_count: 5,
            total_lend_count: 300,
            author: '行龙',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '新世界史（第1卷）  ',
            pub_info: '中信出版集团',
            isbn: '9787508641171',
            lend_count: 5,
            total_lend_count: 300,
            author: '孙隆基',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '甲骨文丛书·湖南人与现代中国  ',
            pub_info: '社会科学文献出版社',
            isbn: '9787509778173',
            lend_count: 5,
            total_lend_count: 300,
            author: '裴士锋',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '耶路撒冷三千年  ',
            pub_info: '民主与建设出版社',
            isbn: '9787513903509',
            lend_count: 5,
            total_lend_count: 300,
            author: '西蒙·蒙蒂菲奥里',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '全球通史 从史前史到21世纪（ 第7版 修订版 中文版 套装上下册）（赠送精美地图）  ',
            pub_info: '北京大学出版社',
            isbn: '10076998',
            lend_count: 5,
            total_lend_count: 300,
            author: '斯塔夫里阿诺斯',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '万历十五年（增订本）  ',
            pub_info: '中华书局',
            isbn: '9787101054491',
            lend_count: 5,
            total_lend_count: 300,
            author: '黄仁宇',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '苦难辉煌（全新修订增补版）  ',
            pub_info: '作家出版社',
            isbn: '9787506379236',
            lend_count: 5,
            total_lend_count: 300,
            author: '金一南',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '甲骨文丛书：天国之秋  ',
            pub_info: '社会科学文献出版社',
            isbn: '9787509752647',
            lend_count: 5,
            total_lend_count: 300,
            author: '裴士锋',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '中国通史（套装上下册）  ',
            pub_info: '中信出版社',
            isbn: '9787508647074',
            lend_count: 5,
            total_lend_count: 300,
            author: '傅乐成',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '甲骨文丛书：金雀花王朝  ',
            pub_info: '社会科学文献出版社',
            isbn: '9787509768129',
            lend_count: 5,
            total_lend_count: 300,
            author: '丹·琼斯',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '甲骨文丛书：阿拉伯的劳伦斯 战争、谎言、帝国愚行与现代中东的形成  ',
            pub_info: '社会科学文献出版社',
            isbn: '9787509759233',
            lend_count: 5,
            total_lend_count: 300,
            author: '斯科特·安德森',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '故宫营造  ',
            pub_info: '中华书局',
            isbn: '9787101109733',
            lend_count: 5,
            total_lend_count: 300,
            author: '单士元',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '用年表读懂中国史  ',
            pub_info: '北京理工大学出版社',
            isbn: '9787564078133',
            lend_count: 5,
            total_lend_count: 300,
            author: '马东峰',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '万历十五年（增订本）  ',
            pub_info: '中华书局',
            isbn: '9787101054491',
            lend_count: 5,
            total_lend_count: 300,
            author: '黄仁宇',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '全球通史 从史前史到21世纪（ 第7版 修订版 中文版 套装上下册）（赠送精美地图）  ',
            pub_info: '北京大学出版社',
            isbn: '10076998',
            lend_count: 5,
            total_lend_count: 300,
            author: '斯塔夫里阿诺斯',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '图说天下·话说中国历史（套装共10册）  ',
            pub_info: '北京联合出版公司',
            isbn: '11143476',
            lend_count: 5,
            total_lend_count: 300,
            author: '龚书铎',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '知行合一·王阳明（1472-1529）  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550230002',
            lend_count: 5,
            total_lend_count: 300,
            author: '度阴山',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '大国崛起之谜 美国、日本、德国、英国、法国（套装共5册）  ',
            pub_info: '北京联合出版公司',
            isbn: '11488382',
            lend_count: 5,
            total_lend_count: 300,
            author: '潜堂',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '耶路撒冷三千年  ',
            pub_info: '民主与建设出版社',
            isbn: '9787513903509',
            lend_count: 5,
            total_lend_count: 300,
            author: '西蒙·蒙蒂菲奥里',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '华杉讲透孙子兵法  ',
            pub_info: '江苏文艺出版社',
            isbn: '9787539978536',
            lend_count: 5,
            total_lend_count: 300,
            author: '华杉',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '知行合一王阳明2：四句话读懂阳明心学  ',
            pub_info: '北京时代华文出版公司',
            isbn: '9787569903188',
            lend_count: 5,
            total_lend_count: 300,
            author: '度阴山',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '明朝那些事儿（套装 全套共7册）  ',
            pub_info: '浙江人民出版社',
            isbn: '10882194',
            lend_count: 5,
            total_lend_count: 300,
            author: '当年明月',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '美国人 从殖民到民主的历程 三部曲（套装共3册）  ',
            pub_info: '上海译文出版社',
            isbn: '9787532768066',
            lend_count: 5,
            total_lend_count: 300,
            author: '丹尼尔·布尔斯廷',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '中国历史的教训  ',
            pub_info: '中信出版社',
            isbn: '9787508650043',
            lend_count: 5,
            total_lend_count: 300,
            author: '习骅',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '易中天中华史第十三卷：隋唐定局  ',
            pub_info: '浙江文艺出版社',
            isbn: '9787533942786',
            lend_count: 5,
            total_lend_count: 300,
            author: '易中天',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '中国的内战 1945-1949年的政治斗争  ',
            pub_info: '当代中国出版社',
            isbn: '9787515404554',
            lend_count: 5,
            total_lend_count: 300,
            author: '胡素珊',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '革命年代（珍藏版）  ',
            pub_info: '广东人民出版社',
            isbn: '9787218061948',
            lend_count: 5,
            total_lend_count: 300,
            author: '高华',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '鸦片战争  ',
            pub_info: '新星出版社',
            isbn: '9787513318020',
            lend_count: 5,
            total_lend_count: 300,
            author: '蓝诗玲',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '说中国：一个不断变化的复杂共同体  ',
            pub_info: '广西师范大学出版社',
            isbn: '9787549564286',
            lend_count: 5,
            total_lend_count: 300,
            author: '许倬云',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '权力的毛细管作用：清代的思想、学术与心态（修订版）  ',
            pub_info: '北京大学出版社',
            isbn: '9787301261484',
            lend_count: 5,
            total_lend_count: 300,
            author: '王汎森',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '罗马灭亡后的地中海世界（套装上下册）  [ ローマ亡き後の地中海世界]',
            pub_info: '中信出版社',
            isbn: '9787508644981',
            lend_count: 5,
            total_lend_count: 300,
            author: '盐野七生',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '历史的经验  ',
            pub_info: '复旦大学出版社',
            isbn: '9787309032390',
            lend_count: 5,
            total_lend_count: 300,
            author: '南怀瑾',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '张鸣说历史：大国的虚与实  ',
            pub_info: '群言出版社',
            isbn: '9787802568679',
            lend_count: 5,
            total_lend_count: 300,
            author: '张鸣',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '美国人 从殖民到民主的历程 三部曲（套装共3册）  ',
            pub_info: '上海译文出版社',
            isbn: '9787532768066',
            lend_count: 5,
            total_lend_count: 300,
            author: '丹尼尔·布尔斯廷',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '三国志（套装上下册）  ',
            pub_info: '中华书局',
            isbn: '9787101077087',
            lend_count: 5,
            total_lend_count: 300,
            author: '陈寿',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '甲午殇思 入选2014中国好书  ',
            pub_info: '上海远东出版社',
            isbn: '9787547608531',
            lend_count: 5,
            total_lend_count: 300,
            author: '刘亚洲',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '人性中的善良天使：暴力为什么会减少（套装上下册）  [The Better Angels of Our Nature]',
            pub_info: '中信出版集团',
            isbn: '9787508648583',
            lend_count: 5,
            total_lend_count: 300,
            author: '斯蒂芬·平克',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '东大爸爸写给我的日本史  ',
            pub_info: '北京联合出版公司',
            isbn: '9787550260474',
            lend_count: 5,
            total_lend_count: 300,
            author: '小岛毅',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '费正清中国史  ',
            pub_info: '吉林出版集团有限责任公司',
            isbn: '9787553462462',
            lend_count: 5,
            total_lend_count: 300,
            author: '费正清',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '历史深处的民国 3 重生  ',
            pub_info: '华文出版社',
            isbn: '9787507544138',
            lend_count: 5,
            total_lend_count: 300,
            author: '江城',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '张鸣说历史：大国的虚与实  ',
            pub_info: '群言出版社',
            isbn: '9787802568679',
            lend_count: 5,
            total_lend_count: 300,
            author: '张鸣',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '南渡北归系列  亲笔签名版 全新增订（未删减版，套装全3册）  ',
            pub_info: '湖南文艺出版社',
            isbn: '11770140',
            lend_count: 5,
            total_lend_count: 300,
            author: '岳南',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '宫崎市定中国史  ',
            pub_info: '浙江人民出版社',
            isbn: '9787213068522',
            lend_count: 5,
            total_lend_count: 300,
            author: '宫崎市定',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '易中天中华史第十三卷：隋唐定局  ',
            pub_info: '浙江文艺出版社',
            isbn: '9787533942786',
            lend_count: 5,
            total_lend_count: 300,
            author: '易中天',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '甲骨文丛书·茶叶大盗：改变世界史的中国茶  ',
            pub_info: '社会科学文献出版社',
            isbn: '9787509779187',
            lend_count: 5,
            total_lend_count: 300,
            author: '萨拉·罗斯',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '权力的毛细管作用：清代的思想、学术与心态（修订版）  ',
            pub_info: '北京大学出版社',
            isbn: '9787301261484',
            lend_count: 5,
            total_lend_count: 300,
            author: '王汎森',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '南渡北归系列 全新增订（未删减版，套装全3册）  ',
            pub_info: '湖南文艺出版社',
            isbn: '11758624',
            lend_count: 5,
            total_lend_count: 300,
            author: '岳南',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '晚明大变局  ',
            pub_info: '中华书局',
            isbn: '9787101111002',
            lend_count: 5,
            total_lend_count: 300,
            author: '樊树志',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '剑桥中国明代史（1368-1644年 3000套装上下卷）  [The Cambridge History of China]',
            pub_info: '中国社会科学出版社',
            isbn: '11180848',
            lend_count: 5,
            total_lend_count: 300,
            author: '剑桥大学',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '家人父子：由人伦探访明清之际士大夫的生活世界  ',
            pub_info: '北京大学出版社',
            isbn: '9787301260838',
            lend_count: 5,
            total_lend_count: 300,
            author: '赵园',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '明清之际士大夫研究  ',
            pub_info: '北京大学出版社',
            isbn: '9787301239179',
            lend_count: 5,
            total_lend_count: 300,
            author: '赵园',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '帝国的溃败  ',
            pub_info: '东方出版社',
            isbn: '9787506082082',
            lend_count: 5,
            total_lend_count: 300,
            author: '张鸣',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '辛亥：摇晃的中国  ',
            pub_info: '广西师范大学出版社',
            isbn: '9787549503247',
            lend_count: 5,
            total_lend_count: 300,
            author: '张鸣',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '新史记（全两册）  ',
            pub_info: '生活·读书·新知三联书店',
            isbn: '11684157',
            lend_count: 5,
            total_lend_count: 300,
            author: '杨早',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '中华人民共和国建国史研究全集（套装共2册）  ',
            pub_info: '江西人民出版社',
            isbn: '11730552',
            lend_count: 5,
            total_lend_count: 300,
            author: '杨奎松',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '阎明复回忆录（套装共两卷）  ',
            pub_info: '人民出版社',
            isbn: '9787010149356',
            lend_count: 5,
            total_lend_count: 300,
            author: '阎明复',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        }),
        knex('books').insert({
            title: '我者与他者：中国历史上的内外分际（精装）  ',
            pub_info: '生活·读书·新知三联书店',
            isbn: '9787108053978',
            lend_count: 5,
            total_lend_count: 300,
            author: '许倬云',
            stock: 10,
            pub_year: 2015,
            category_char: 'K',
            status: 0
        })
    );
};
